---
# tasks_include for keybase_unseal by @bbaassssiiee

- name: Vault API reachable?
  # Attempt to help with long lines > 160 issues
  vars:
    vault_proto: "{{ vault_tls_disable | ternary('http', 'https') }}"
    # yamllint disable-line rule:line-length
    vault_addr: "{{ (vault_address == '0.0.0.0') | ternary('127.0.0.1', vault_address) }}"
  uri:
    validate_certs: "{{ validate_certs_during_api_reachable_check | bool }}"
    url: "{{ vault_proto }}://{{ vault_addr }}:{{ vault_port }}/v1/sys/health"
    method: GET
    # 200 if initialized, unsealed, and active
    # 429 if unsealed and standby
    # 472 if data recovery mode replication secondary and active
    # 473 if performance standby
    # 501 if not initialized
    # 503 if sealed
    # See: https://www.vaultproject.io/api/system/health.html
    status_code: 200, 503, 200, 429, 473, 501, 503
    body_format: json
  register: check_result
  retries: 6
  until: check_result is succeeded
  delay: 10
  changed_when: false
  tags:
    - check_vault
    - init
    - unseal
    - seal

- name: Vault status
  debug:
    msg: "Vault is {{ item.value }}"
  loop: "{{ lookup('dict', vault_http_status) }}"
  when: "'{{ check_result.status }}' in item.key"
  tags:
    - check_vault
    - init
    - unseal
    - seal

...
